package com.demo.kafkaProducer.config.avro.record; /**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroProducerSync extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -9193687514861607515L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroProducerSync\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"ownerName\",\"type\":\"string\"},{\"name\":\"productName\",\"type\":\"string\"},{\"name\":\"quantity\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroProducerSync> ENCODER =
      new BinaryMessageEncoder<AvroProducerSync>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroProducerSync> DECODER =
      new BinaryMessageDecoder<AvroProducerSync>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<AvroProducerSync> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<AvroProducerSync> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AvroProducerSync>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this com.demo.kafka.config.avro.record.AvroProducerSync to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a com.demo.kafka.config.avro.record.AvroProducerSync from a ByteBuffer. */
  public static AvroProducerSync fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long id;
  @Deprecated public java.lang.CharSequence ownerName;
  @Deprecated public java.lang.CharSequence productName;
  @Deprecated public int quantity;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroProducerSync() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param ownerName The new value for ownerName
   * @param productName The new value for productName
   * @param quantity The new value for quantity
   */
  public AvroProducerSync(java.lang.Long id, java.lang.CharSequence ownerName, java.lang.CharSequence productName, java.lang.Integer quantity) {
    this.id = id;
    this.ownerName = ownerName;
    this.productName = productName;
    this.quantity = quantity;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return ownerName;
    case 2: return productName;
    case 3: return quantity;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: ownerName = (java.lang.CharSequence)value$; break;
    case 2: productName = (java.lang.CharSequence)value$; break;
    case 3: quantity = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'ownerName' field.
   * @return The value of the 'ownerName' field.
   */
  public java.lang.CharSequence getOwnerName() {
    return ownerName;
  }

  /**
   * Sets the value of the 'ownerName' field.
   * @param value the value to set.
   */
  public void setOwnerName(java.lang.CharSequence value) {
    this.ownerName = value;
  }

  /**
   * Gets the value of the 'productName' field.
   * @return The value of the 'productName' field.
   */
  public java.lang.CharSequence getProductName() {
    return productName;
  }

  /**
   * Sets the value of the 'productName' field.
   * @param value the value to set.
   */
  public void setProductName(java.lang.CharSequence value) {
    this.productName = value;
  }

  /**
   * Gets the value of the 'quantity' field.
   * @return The value of the 'quantity' field.
   */
  public java.lang.Integer getQuantity() {
    return quantity;
  }

  /**
   * Sets the value of the 'quantity' field.
   * @param value the value to set.
   */
  public void setQuantity(java.lang.Integer value) {
    this.quantity = value;
  }

  /**
   * Creates a new com.demo.kafka.config.avro.record.AvroProducerSync RecordBuilder.
   * @return A new com.demo.kafka.config.avro.record.AvroProducerSync RecordBuilder
   */
  public static AvroProducerSync.Builder newBuilder() {
    return new AvroProducerSync.Builder();
  }

  /**
   * Creates a new com.demo.kafka.config.avro.record.AvroProducerSync RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new com.demo.kafka.config.avro.record.AvroProducerSync RecordBuilder
   */
  public static AvroProducerSync.Builder newBuilder(AvroProducerSync.Builder other) {
    return new AvroProducerSync.Builder(other);
  }

  /**
   * Creates a new com.demo.kafka.config.avro.record.AvroProducerSync RecordBuilder by copying an existing com.demo.kafka.config.avro.record.AvroProducerSync instance.
   * @param other The existing instance to copy.
   * @return A new com.demo.kafka.config.avro.record.AvroProducerSync RecordBuilder
   */
  public static AvroProducerSync.Builder newBuilder(AvroProducerSync other) {
    return new AvroProducerSync.Builder(other);
  }

  /**
   * RecordBuilder for com.demo.kafka.config.avro.record.AvroProducerSync instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroProducerSync>
    implements org.apache.avro.data.RecordBuilder<AvroProducerSync> {

    private long id;
    private java.lang.CharSequence ownerName;
    private java.lang.CharSequence productName;
    private int quantity;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(AvroProducerSync.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ownerName)) {
        this.ownerName = data().deepCopy(fields()[1].schema(), other.ownerName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.productName)) {
        this.productName = data().deepCopy(fields()[2].schema(), other.productName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.quantity)) {
        this.quantity = data().deepCopy(fields()[3].schema(), other.quantity);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing com.demo.kafka.config.avro.record.AvroProducerSync instance
     * @param other The existing instance to copy.
     */
    private Builder(AvroProducerSync other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ownerName)) {
        this.ownerName = data().deepCopy(fields()[1].schema(), other.ownerName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.productName)) {
        this.productName = data().deepCopy(fields()[2].schema(), other.productName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.quantity)) {
        this.quantity = data().deepCopy(fields()[3].schema(), other.quantity);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Long getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public AvroProducerSync.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public AvroProducerSync.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'ownerName' field.
      * @return The value.
      */
    public java.lang.CharSequence getOwnerName() {
      return ownerName;
    }

    /**
      * Sets the value of the 'ownerName' field.
      * @param value The value of 'ownerName'.
      * @return This builder.
      */
    public AvroProducerSync.Builder setOwnerName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.ownerName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'ownerName' field has been set.
      * @return True if the 'ownerName' field has been set, false otherwise.
      */
    public boolean hasOwnerName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'ownerName' field.
      * @return This builder.
      */
    public AvroProducerSync.Builder clearOwnerName() {
      ownerName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'productName' field.
      * @return The value.
      */
    public java.lang.CharSequence getProductName() {
      return productName;
    }

    /**
      * Sets the value of the 'productName' field.
      * @param value The value of 'productName'.
      * @return This builder.
      */
    public AvroProducerSync.Builder setProductName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.productName = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'productName' field has been set.
      * @return True if the 'productName' field has been set, false otherwise.
      */
    public boolean hasProductName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'productName' field.
      * @return This builder.
      */
    public AvroProducerSync.Builder clearProductName() {
      productName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'quantity' field.
      * @return The value.
      */
    public java.lang.Integer getQuantity() {
      return quantity;
    }

    /**
      * Sets the value of the 'quantity' field.
      * @param value The value of 'quantity'.
      * @return This builder.
      */
    public AvroProducerSync.Builder setQuantity(int value) {
      validate(fields()[3], value);
      this.quantity = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'quantity' field has been set.
      * @return True if the 'quantity' field has been set, false otherwise.
      */
    public boolean hasQuantity() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'quantity' field.
      * @return This builder.
      */
    public AvroProducerSync.Builder clearQuantity() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroProducerSync build() {
      try {
        AvroProducerSync record = new AvroProducerSync();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.ownerName = fieldSetFlags()[1] ? this.ownerName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.productName = fieldSetFlags()[2] ? this.productName : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.quantity = fieldSetFlags()[3] ? this.quantity : (java.lang.Integer) defaultValue(fields()[3]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroProducerSync>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroProducerSync>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroProducerSync>
    READER$ = (org.apache.avro.io.DatumReader<AvroProducerSync>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
