package com.demo.kafka.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProducerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProducerAllPropertiesEquals(Producer expected, Producer actual) {
        assertProducerAutoGeneratedPropertiesEquals(expected, actual);
        assertProducerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProducerAllUpdatablePropertiesEquals(Producer expected, Producer actual) {
        assertProducerUpdatableFieldsEquals(expected, actual);
        assertProducerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProducerAutoGeneratedPropertiesEquals(Producer expected, Producer actual) {
        assertThat(expected)
            .as("Verify Producer auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProducerUpdatableFieldsEquals(Producer expected, Producer actual) {
        assertThat(expected)
            .as("Verify Producer relevant properties")
            .satisfies(e -> assertThat(e.getOwnerName()).as("check ownerName").isEqualTo(actual.getOwnerName()))
            .satisfies(e -> assertThat(e.getProductName()).as("check productName").isEqualTo(actual.getProductName()))
            .satisfies(e -> assertThat(e.getQuantity()).as("check quantity").isEqualTo(actual.getQuantity()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProducerUpdatableRelationshipsEquals(Producer expected, Producer actual) {}
}
